# Generated by Django 3.0.5 on 2020-10-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoapp', '0002_auto_20201001_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(default=10, null=True)),
                ('roll_no', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Poll',
        ),
    ]
