# Generated by Django 3.0.5 on 2020-10-02 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongoapp', '0004_auto_20201002_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='no_of_items',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
