# Generated by Django 3.0.5 on 2020-10-02 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongoapp', '0006_auto_20201002_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='no_of_items',
            new_name='noo_of_items',
        ),
    ]
