# Generated by Django 3.0.5 on 2020-10-02 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mongoapp', '0007_auto_20201002_1212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='noo_of_items',
            new_name='no_of_items_left',
        ),
    ]
